const http = require('http');
const PORT = 3000;
const cheerio = require('cheerio');
const axios = require('axios');
const TelegramBot = require('node-telegram-bot-api');
const express = require('express');
const app = express();


const rel = 'https://economictimes.indiatimes.com/reliance-industries-ltd/stocks/companyid-13215.cms';
const bse = 'https://economictimes.indiatimes.com/bse-ltd/stocks/companyid-2809.cms';
const relf = 'https://economictimes.indiatimes.com/reliance-industries-ltd/stocks/companyid-13215.cms';
const jio = 'https://economictimes.indiatimes.com/jio-financial-services-ltd/stocks/companyid-14555.cms';
const bikaji = 'https://economictimes.indiatimes.com/bikaji-foods-international-ltd/stocks/companyid-2099545.cms';
const irb = 'https://economictimes.indiatimes.com/irb-infrastructure-developers-ltd/stocks/companyid-20738.cms';
const hindustancopper = 'https://economictimes.indiatimes.com/hindustan-copper-ltd/stocks/companyid-11733.cms';
const arvind = 'https://economictimes.indiatimes.com/arvind-ltd/stocks/companyid-14037.cms';
const adani = 'https://economictimes.indiatimes.com/adani-power-ltd/stocks/companyid-23479.cms';
const pnb = 'https://economictimes.indiatimes.com/punjab-national-bank/stocks/companyid-11585.cms';
const rbl = 'https://economictimes.indiatimes.com/rbl-bank-ltd/stocks/companyid-7750.cms';
const marksans = 'https://economictimes.indiatimes.com/marksans-pharma-ltd/stocks/companyid-10542.cms';
const minda = 'https://economictimes.indiatimes.com/minda-corporation-ltd/stocks/companyid-30624.cms';
const ushamartin = 'https://economictimes.indiatimes.com/usha-martin-ltd/stocks/companyid-12833.cms';
const century = 'https://economictimes.indiatimes.com/century-textiles-industries-ltd/stocks/companyid-13905.cms';
const anandrathi = 'https://economictimes.indiatimes.com/anand-rathi-wealth-ltd/stocks/companyid-2020300.cms';
const agies = 'https://economictimes.indiatimes.com/aegis-logistics-ltd/stocks/companyid-23.cms';
const karnatka = 'https://economictimes.indiatimes.com/karnataka-bank-ltd/stocks/companyid-12259.cms';
const heg = 'https://economictimes.indiatimes.com/heg-ltd/stocks/companyid-13630.cms';
const reltail = 'https://economictimes.indiatimes.com/railtel-corporation-of-india-ltd/stocks/companyid-16503.cms';
const hfcl = 'https://economictimes.indiatimes.com/hfcl-ltd/stocks/companyid-13649.cms';
const shipping = 'https://economictimes.indiatimes.com/shipping-corporation-of-india-ltd/stocks/companyid-11972.cms';
const deltacorp = 'https://economictimes.indiatimes.com/delta-corp-ltd/stocks/companyid-9453.cms';
const sula = 'https://economictimes.indiatimes.com/sula-vineyards-ltd/stocks/companyid-2101578.cms';
const hindalko = 'https://economictimes.indiatimes.com/hindalco-industries-ltd/stocks/companyid-13637.cms';
const justdial = 'https://economictimes.indiatimes.com/just-dial-ltd/stocks/companyid-45529.cms';
const sjvn = 'https://economictimes.indiatimes.com/sjvn-ltd/stocks/companyid-18460.cms';
const grephiteindia = 'https://economictimes.indiatimes.com/graphite-india-ltd/stocks/companyid-13916.cms';
const parimalpharma = 'https://economictimes.indiatimes.com/piramal-pharma-ltd/stocks/companyid-2094561.cms';
const tv18 = 'https://economictimes.indiatimes.com/tv18-broadcast-ltd/stocks/companyid-15481.cms';
const maninfra = 'https://economictimes.indiatimes.com/man-infraconstruction-ltd/stocks/companyid-22649.cms';
const jammu = 'https://economictimes.indiatimes.com/jammu-kashmir-bank-ltd/stocks/companyid-8611.cms';
const stride = 'https://economictimes.indiatimes.com/strides-pharma-science-ltd/stocks/companyid-2118.cms';
const sequent = 'https://economictimes.indiatimes.com/sequent-scientific-ltd/stocks/companyid-3782.cms';
const anupam = 'https://economictimes.indiatimes.com/anupam-rasayan-india-ltd/stocks/companyid-45694.cms';
const tvs = 'https://economictimes.indiatimes.com/tvs-srichakra-ltd/stocks/companyid-12987.cms';
const gail = 'https://economictimes.indiatimes.com/gail-india-ltd/stocks/companyid-4845.cms';
const auribindo = 'https://economictimes.indiatimes.com/aurobindo-pharma-ltd/stocks/companyid-8279.cms';
const jindalsp = 'https://economictimes.indiatimes.com/jindal-steel-power-ltd/stocks/companyid-4355.cms';
const jmfinance = 'https://economictimes.indiatimes.com/jm-financial-ltd/stocks/companyid-12633.cms';
const nitinspinner = 'https://economictimes.indiatimes.com/nitin-spinners-ltd/stocks/companyid-17841.cms';
const granules = 'https://economictimes.indiatimes.com/granules-india-ltd/stocks/companyid-6991.cms';
const archean = 'https://economictimes.indiatimes.com/archean-chemical-industries-ltd/stocks/companyid-55288.cms';
const adanienter = 'https://economictimes.indiatimes.com/adani-enterprises-ltd/stocks/companyid-9074.cms';
const polymadicure = 'https://economictimes.indiatimes.com/poly-medicure-ltd/stocks/companyid-4586.cms';
const eidparry = 'https://economictimes.indiatimes.com/eid-parry-india-ltd/stocks/companyid-13818.cms';
const orchid = 'https://economictimes.indiatimes.com/orchid-pharma-ltd/stocks/companyid-10568.cms';
const rblbank = 'https://economictimes.indiatimes.com/rbl-bank-ltd/stocks/companyid-7750.cms';
const restaurant = 'https://economictimes.indiatimes.com/restaurant-brands-asia-ltd/stocks/companyid-1997181.cms';
const orrisa = 'https://economictimes.indiatimes.com/the-orissa-minerals-development-company-ltd/stocks/companyid-412.cms';
const ritesh = 'https://economictimes.indiatimes.com/rites-ltd/stocks/companyid-18469.cms';
const garware = 'https://economictimes.indiatimes.com/garware-hi-tech-films-ltd/stocks/companyid-13746.cms';
const arbindopahrma = 'https://economictimes.indiatimes.com/aurobindo-pharma-ltd/stocks/companyid-8279.cms';
const rishabhins = 'https://economictimes.indiatimes.com/rishabh-instruments-ltd/stocks/companyid-50196.cms';
const neogen = 'https://economictimes.indiatimes.com/neogen-chemicals-ltd/stocks/companyid-1942599.cms';
const nueland = 'https://economictimes.indiatimes.com/neuland-laboratories-ltd/stocks/companyid-9051.cms';
const metropolish = 'https://economictimes.indiatimes.com/metropolis-healthcare-ltd/stocks/companyid-16325.cms';
const keystone = 'https://economictimes.indiatimes.com/keystone-realtors-ltd/stocks/companyid-61456.cms';
const grasim = 'https://economictimes.indiatimes.com/grasim-industries-ltd/stocks/companyid-13696.cms';
const jash = 'https://economictimes.indiatimes.com/jash-engineering-ltd/stocks/companyid-47196.cms';
const indoco = 'https://economictimes.indiatimes.com/indoco-remedies-ltd/stocks/companyid-792.cms';
const cipla = 'https://economictimes.indiatimes.com/cipla-ltd/stocks/companyid-13917.cms';
const bestagro = 'https://www.tickertape.in/stocks/best-agrolife-BES';
const indianenergy = 'https://economictimes.indiatimes.com/indian-energy-exchange-ltd/stocks/companyid-20870.cms';
const engeenerindia = 'https://economictimes.indiatimes.com/engineers-india-ltd/stocks/companyid-4582.cms';
const ncc = 'https://economictimes.indiatimes.com/ncc-ltd/stocks/companyid-11234.cms';
const asterdm = 'https://economictimes.indiatimes.com/aster-dm-healthcare-ltd/stocks/companyid-67489.cms';
const latent = 'https://economictimes.indiatimes.com/latent-view-analytics-ltd/stocks/companyid-2018256.cms';
const pix = 'https://economictimes.indiatimes.com/pix-transmissions-ltd/stocks/companyid-13281.cms';
const ksb = 'https://economictimes.indiatimes.com/ksb-ltd/stocks/companyid-13500.cms';
const hpadhesive = 'https://economictimes.indiatimes.com/hp-adhesives-ltd/stocks/companyid-2020833.cms';
const vardhman = 'https://economictimes.indiatimes.com/vardhman-textiles-ltd/stocks/companyid-11897.cms';
const ambuja = 'https://economictimes.indiatimes.com/ambuja-cements-ltd/stocks/companyid-13643.cms';
const epl = 'https://economictimes.indiatimes.com/epl-ltd/stocks/companyid-13764.cms';
const on97 = 'https://economictimes.indiatimes.com/one97-communications-ltd/stocks/companyid-2017785.cms';
const confipetrin = 'https://economictimes.indiatimes.com/confidence-petroleum-india-ltd/stocks/companyid-8227.cms';
const agigreenpack = 'https://economictimes.indiatimes.com/agi-greenpac-ltd/stocks/companyid-13621.cms';
const primochemi = 'https://economictimes.indiatimes.com/primo-chemicals-ltd/stocks/companyid-13243.cms';
const sp = 'https://economictimes.indiatimes.com/s-p-apparels-ltd/stocks/companyid-64531.cms';
const indianhumepipe = 'https://economictimes.indiatimes.com/indian-hume-pipe-company-ltd/stocks/companyid-13587.cms';
const taj = 'https://economictimes.indiatimes.com/taj-gvk-hotels-resorts-ltd/stocks/companyid-3295.cms';
const lupin = 'https://economictimes.indiatimes.com/lupin-ltd/stocks/companyid-10743.cms';
const sunpharmadv = 'https://economictimes.indiatimes.com/sun-pharma-advanced-research-company-ltd/stocks/companyid-18315.cms';
const orient = 'https://economictimes.indiatimes.com/orient-paper-industries-ltd/stocks/companyid-13319.cms';
const bharatrasayan = 'https://economictimes.indiatimes.com/bharat-rasayan-ltd/stocks/companyid-10986.cms';
const nacl = 'https://economictimes.indiatimes.com/nacl-industries-ltd/stocks/companyid-8650.cms';
const irm = 'https://economictimes.indiatimes.com/irm-energy-ltd/stocks/companyid-2153874.cms';
const vimla = 'https://economictimes.indiatimes.com/vimta-labs-ltd/stocks/companyid-10686.cms';

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hellohhh World!');
});

server.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}/`);
});
